package PCC

#imports

import com.sapienter.jbilling.server.item.PricingField
import com.sapienter.jbilling.server.mediation.task.MediationResult
import com.sapienter.jbilling.server.item.db.ItemDTO
import com.sapienter.jbilling.server.order.db.OrderLineDTO;
import com.sapienter.jbilling.server.order.db.OrderLineDAS;
import com.sapienter.jbilling.server.order.db.OrderDTO;
import com.sapienter.jbilling.server.item.tasks.SubscriptionResult
import com.sapienter.jbilling.server.order.OrderLineBL;
import com.sapienter.jbilling.server.order.OrderBL;
import com.sapienter.jbilling.server.item.tasks.PricingResult
import java.util.ArrayList;
import java.math.BigDecimal;
import java.util.List;
import org.apache.log4j.Logger;

rule 'PCC rule'
when
       OrderLineDTO( itemId == 1, $quantity : quantity )
then

end

